### PR TITLE
Added documentation for namespace

### PR DESCRIPTION
**Pull request by devlead**
Added name space documentation for the auto generated cakebuild.net docs.

### CODE REVIEW

**Comment by RichiCoder1** [comment]
NameSpaceDoc? Is that new?

**Comment by devlead** [comment]
It's a Cake unique concept as there's no standard to document namespaces.
You can see result [here](http://cakebuild.net/api)

**Comment by patriksvensson** [comment]
Not Cake specific. Supported by SandCastle and other documentation tools.

**Comment by devlead** [comment]
Cool didn't know that :+1:

**Pull request merged**
